version: '3'

services:
  nginx:
    container_name: nginx
    build: requirements/mariadb/.
    # image: nginx:latest
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - frontend
    context: requirements/nginx
    dockerfile: Dockerfile
    env_file: .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    expose:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - frontend
      - backend
    context: requirements/wordpress
    dockerfile: Dockerfile
    env_file: .env
    restart: on-failure

  mariadb:
    container_name: mariadb
    expose:
      - 3306
    build: requirements/mariadb/.
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
    context: requirements/mariadb
    dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped


volumes:
  wordpress_data:
    driver: local
    driver_opts:
    type: 'none'
    o: 'bind'
    device: '/Users/fgrasset/data/wordpress'

  mariadb_data:
    driver: local
    driver_opts:
    type: 'none'
    o: 'bind'
    device: '/Users/fgrasset/data/mariadb'


networks:
  frontend:
    driver: bridge

  backend:
    driver: bridge
