version: '3'

volumes:
  mariadb_data:
    driver: local
    name: mariadb_data
    driver_opts:
      device: /Users/fgrasset/data/mariadb/
      type: none
      o: bind

  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      device: /Users/fgrasset/data/wordpress/
      type: none
      o: bind

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file: .env
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file: .env
    restart: on-failure

networks:
  inception:
    driver: bridge
